### ISSUE TITLE
nightfall: panics during streaming.

### ISSUE THREAD

**Issue by mental32** [vgarleanu/dim#54]
on the experimental branch `fix-video-streaming` I get playback halting it looks like its just buffering on the UI side but if you check out the server stderr I see panics in nightfall

```
Mar 24 21:35:10.404 INFO request, uri: "/api/v1/stream/9c374e3a-4d2e-4388-9dbd-38185ee28c60/data/5.m4s", method: Get
try wait, ffmpeg died, killing
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/mental/.cargo/git/checkouts/nightfall-b84a4513de79ba91/9ade607/src/lib.rs:177:53
Mar 24 21:35:38.464 INFO response, status: 500 Internal Server Error, route: GET /api/v1/stream/<id>/data/<chunk..> [2] (get_chunk)
try wait, ffmpeg died, killing
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/mental/.cargo/git/checkouts/nightfall-b84a4513de79ba91/9ade607/src/lib.rs:177:53
Mar 24 21:35:38.473 INFO response, status: 500 Internal Server Error, route: GET /api/v1/stream/<id>/data/<chunk..> [2] (get_chunk)
```

**Comment by mental32** [comment]
potential blocker for #4 ?

**Comment by mental32** [comment]
update: panics do still occur but they don't mess up playback.
